# Repo of operator and cluster default images. Default is polardbx.
imageRepo: polardbx-opensource-registry.cn-beijing.cr.aliyuncs.com/polardbx

# Image names of operator components. By default, operator uses the
# images tagged with { .Chart.AppVersion }. Overwrite the tags with
# imageTag.
images:
  polardbxOperator: polardbx-operator
  hpfs: polardbx-hpfs
  toolsUpdater: xstore-tools
  probeProxy: probe-proxy
  polardbxExporter: polardbx-exporter
  polardbxInit: polardbx-init
  polardbxJob: polardbx-job
  polardbxClinic: polardbx-clinic

# Default image tag. Use app version if not specified or 'latest' if useLatestImage is true.
imageTag: v1.7.0

# version will be written to pxc and xstore annotation 
version: v1.7.0

# Uses the latest images for operator components.
useLatestImage: false

# Image pull policy of operator pods.
imagePullPolicy: IfNotPresent

# Image pull secrets of operator pods.
imagePullSecrets:

# Default settings for PolarDB-X Cluster.
clusterDefaults:
  version: latest
  images:
    galaxysql: polardbx-sql
    galaxyengine: polardbx-engine-2.0
    galaxycdc: polardbx-cdc

# Configuration of Kubernetes hosts.
node:
  # Paths on nodes to be used by the operator.
  volumes:
    # Data volume, used for storing data of DN, caches and tools
    # used by the operator.
    data: /data
    log: /data-log
    filestream: /filestream

# Service account of operator pods.
serviceAccount: polardbx-operator

# Configuration of controller manager.
controllerManager:
  name: polardbx-controller-manager
  replicas: 1

  # Feature gates of controller manager.
  #   + EnforceQoSGuaranteed, enforces the pod to be Guaranteed QoS by setting resources on
  #     containers like exporter and prober. Disabled by default.
  featureGates: [ ]

  config:
    scheduler:
      # Allow schedule PolarDB-X pod to master node.
      # Default is true.
      allowScheduleOnMaster: true
      # Enable resource controller of ACK container service.
      # Default is true.
      enableAliyunAckResourceController: true

    # Create an exporter sidecar in each PolarDB-X pod if enabled.
    # Default is true.
    enableExporters: true

    # Container settings of PolarDB-X pods.
    container:
      privileged: false
      forceCGroup: false

  nodeSelector: { }
  affinity: { }
  tolerations: { }

  # Resource usage of controller manager pod.
  resources:
    requests:
      cpu: 100m
      memory: 50Mi

  # Denote whether to use the same time zone as the host machine for the operator
  useHostTimeZone: true

# Settings for host path file service.
hostPathFileService:
  name: polardbx-hpfs
  ossEndpoint: xxx
  ossAccessKey: xxx
  ossAccessSecret: xxx
  ossBucket: xxx
  port: 6543
  fsPort: 6643
  fsMinFlow: 1048576  # 1MB/s
  fsMaxFlow: 104857600 # 100MB/s
  fsTotalFlow: 524288000 # 500MB/s
  fsBufferSize: 2097152 # 2MB
  sinks:
    - name: default
      type: s3
      endpoint: xxx
      accessKey: xxx
      accessSecret: xxxxx
      bucket: xxx
      useSSL: false
      bucketLookupType: dns # auto, dns, path
      uploadPartMaxSize: 629145600 # 300MB
    - name: default
      type: oss
      endpoint: xxx
      accessKey: xxx
      accessSecret: xxxxx
      bucket: xxx
    - name: default
      type: sftp
      host: xxxxx
      port: 22
      user: admin
      password: xxxx
      rootPath: /xxx
  cpuBind:
    strategy: auto

  resources:
    requests:
      cpu: 100m
      memory: 50Mi

# Settings for xstore tools updater.
toolsUpdater:
  name: polardbx-tools-updater


kubectlImage: "bitnami/kubectl:latest"

# Settings for webhooks.
webhook:
  serviceName: polardbx-admission-webhook
  defaults:
    protocolVersion: 8.0
    storageEngine: galaxy
    serviceType: ClusterIP
    upgradeStrategy: RollingUpgrade

# Extensions.
extension:
  # Ext configs.
  config:
    images:
      store:
    security:
      
clinic:
  resources:
    requests:
      cpu: 100m
      memory: 50Mi
    limits:
      cpu: 1
      memory: 1Gi